# Generated by Django 5.2.9 on 2025-12-28 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Terrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('image_url', models.URLField(blank=True)),
                ('note_moyenne', models.FloatField(default=0.0)),
                ('proprietaire', models.ForeignKey(limit_choices_to={'type_utilisateur': 'PROPRIETAIRE'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField()),
                ('commentaire', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(limit_choices_to={'type_utilisateur': 'STANDARD'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('terrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='terrains.terrain')),
            ],
        ),
        migrations.CreateModel(
            name='CreneauHoraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('tarif', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('disponible', models.BooleanField(default=True)),
                ('terrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='terrains.terrain')),
            ],
        ),
    ]
