# Generated by Django 5.2.9 on 2025-12-28 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terrains', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='creneauhoraire',
            unique_together={('terrain', 'date', 'heure_debut')},
        ),
    ]
