# Generated by Django 5.2.9 on 2025-12-29 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terrains', '0002_alter_creneauhoraire_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creneauhoraire',
            options={'verbose_name': 'Créneau Horaire', 'verbose_name_plural': 'Créneaux Horaires'},
        ),
    ]
