# Generated by Django 5.2.9 on 2025-12-29 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrains', '0003_alter_creneauhoraire_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='terrain',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='terrain',
            name='valide',
            field=models.BooleanField(default=False, verbose_name="Validé par l'admin"),
        ),
    ]
