# Generated by Django 5.2.9 on 2025-12-28 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terrains', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('createur', models.ForeignKey(limit_choices_to={'type_utilisateur': 'STANDARD'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('membres', models.ManyToManyField(limit_choices_to={'type_utilisateur': 'STANDARD'}, related_name='groupes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_reservation', models.CharField(choices=[('INDIVIDUELLE', 'Individuelle'), ('GROUPE', 'Groupe'), ('ORGANISATION', 'Organisation')], max_length=20)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En Attente'), ('CONFIRMEE', 'Confirmee'), ('ANNULEE', 'Annulee'), ('PAYEE', 'Payee'), ('REMBOURSEE', 'Remboursee')], default='EN_ATTENTE', max_length=20)),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('creneau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terrains.creneauhoraire')),
                ('groupe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.groupe')),
                ('utilisateur', models.ForeignKey(limit_choices_to={'type_utilisateur': 'STANDARD'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('methode', models.CharField(choices=[('CARTE', 'Carte'), ('MOBILE', 'Mobile'), ('TRANSFERT', 'Transfert')], max_length=20)),
                ('reference_transaction', models.CharField(max_length=100, unique=True)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservations.reservation')),
            ],
        ),
    ]
